////
////  SnakkAdMobStubs.h
////  Snakk-iOS-Sample
////
////  Created by Nick Penteado on 9/27/12.
////
////
////  This file should only be included if you're NOT using AdMob in your project AND you require the -ObjC Linker flag...
////
//
//#ifndef Snakk_iOS_Sample_SnakkAdMobStubs_h
//#define Snakk_iOS_Sample_SnakkAdMobStubs_h
//
//
//@protocol GADMAdNetworkAdapter <NSObject>
//@end
//
//@protocol GADMAdNetworkConnector<NSObject>
//@end
//
//@protocol GADAdNetworkExtras <NSObject>
//@end
//
//typedef enum {
//    kGADMBannerAnimationTypeNone           = 0,ta
//    kGADMBannerAnimationTypeFlipFromLeft   = 1,
//    kGADMBannerAnimationTypeFlipFromRight  = 2,
//    kGADMBannerAnimationTypeCurlUp         = 3,
//    kGADMBannerAnimationTypeCurlDown       = 4,
//    kGADMBannerAnimationTypeSlideFromLeft  = 5,
//    kGADMBannerAnimationTypeSlideFromRight = 6,
//    kGADMBannerAnimationTypeFadeIn         = 7,
//    kGADMBannerAnimationTypeRandom         = 8,
//} GADMBannerAnimationType;
//
//typedef struct GADAdSize {
//    CGSize size;
//    NSUInteger flags;
//} GADAdSize;
//
//#pragma mark Standard Sizes
//
//// iPhone and iPod Touch ad size. Typically 320x50.
//extern GADAdSize const kGADAdSizeBanner;
//
//// Medium Rectangle size for the iPad (especially in a UISplitView's left pane).
//// Typically 300x250.
//extern GADAdSize const kGADAdSizeMediumRectangle;
//
//// Full Banner size for the iPad (especially in a UIPopoverController or in
//// UIModalPresentationFormSheet). Typically 468x60.
//extern GADAdSize const kGADAdSizeFullBanner;
//
//// Leaderboard size for the iPad. Typically 728x90.
//extern GADAdSize const kGADAdSizeLeaderboard;
//
//// Skyscraper size for the iPad. Mediation only. AdMob/Google does not offer
//// this size. Typically 120x600.
//extern GADAdSize const kGADAdSizeSkyscraper;
//
//// An ad size that spans the full width of the application in portrait
//// orientation. The height is typically 50 pixels on an iPhone/iPod UI, and 90
//// pixels tall on an iPad UI.
//extern GADAdSize const kGADAdSizeSmartBannerPortrait;
//
//// An ad size that spans the full width of the application in landscape
//// orientation. The height is typically 32 pixels on an iPhone/iPod UI, and 90
//// pixels tall on an iPad UI.
//extern GADAdSize const kGADAdSizeSmartBannerLandscape;
//
//// Invalid ad size marker.
//extern GADAdSize const kGADAdSizeInvalid;
//
//#pragma mark Custom Sizes
//
//// Given a CGSize, return a custom GADAdSize. Use this only if you require a
//// non-standard size, otherwise, use one of the standard size constants above.
//GADAdSize GADAdSizeFromCGSize(CGSize size) { return kGADAdSizeInvalid; }
//
//// Get a custom GADAdSize that spans the full width of the application in
//// portrait orientation with the height provided.
//GADAdSize GADAdSizeFullWidthPortraitWithHeight(CGFloat height) { return kGADAdSizeInvalid; }
//
//// Get a custom GADAdSize that spans the full width of the application in
//// landscape orientation with the height provided.
//GADAdSize GADAdSizeFullWidthLandscapeWithHeight(CGFloat height) { return kGADAdSizeInvalid; }
//
//#pragma mark Convenience Functions
//
//// Checks whether the two GADAdSizes are equal.
//BOOL GADAdSizeEqualToSize(GADAdSize size1, GADAdSize size2) { return false; }
//
//// Given a GADAdSize constant, returns a CGSize. If the GADAdSize is unknown,
//// returns CGSizeZero.
//CGSize CGSizeFromGADAdSize(GADAdSize size) { return CGSizeZero; }
//
//// Determines if |size| is one of the predefined constants, or a custom
//// GADAdSize generated by FromCGSize.
//BOOL IsGADAdSizeValid(GADAdSize size) { return false; }
//
//// Given a GADAdSize constant, returns a NSString describing the GADAdSize.
//NSString *NSStringFromGADAdSize(GADAdSize size) { return nil; }
//
//#endif
